### ISSUE TITLE
find all setup required

### ISSUE THREAD

**Issue by nrvivek23** [nrvivek23/CrossPlatformAppium#5]
Go through all the smoke suites

Find all the account required
Eg: email, facebook, googlePlus [for each flow]

Identify and keep valid phone numbers,

Identify and keep deals and stores that will always show

**Comment by JoeMoses** [comment]
googlePlus: joeshopkick2@gmail.com
facebook: joe@shopkick.com
email: p@p.com; pswd: pppppp
